# inflator.toml syntax documentation: https://github.com/faretek1/inflator#inflator
name = "cloud_requests"
version = "v0.0.0"
username = "FAReTek1"

[dependencies]
char = "https://github.com/FAReTek1/char"
string = "https://github.com/FAReTek1/string"